# Generated by Django 5.1.2 on 2024-11-25 08:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('order_sn', models.CharField(editable=False, max_length=50, verbose_name='订单号')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总价')),
                ('pay_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='实际支付金额')),
                ('receiver', models.CharField(max_length=50, verbose_name='收货人')),
                ('address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('status', models.SmallIntegerField(choices=[(0, '待支付'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成'), (5, '已取消'), (6, '已退款'), (7, '待核销')], default=0, verbose_name='订单状态')),
                ('delivery_type', models.SmallIntegerField(choices=[(0, '自提'), (1, '快递'), (2, '其他')], default=0, verbose_name='配送方式')),
                ('delivery_id', models.CharField(blank=True, default='', max_length=50, verbose_name='快递单号')),
                ('pay_type', models.SmallIntegerField(choices=[(0, '支付宝支付'), (1, '微信支付'), (2, '货到付款')], default=0, verbose_name='支付方式')),
                ('pay_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='支付流水号')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('is_refund', models.BooleanField(default=False, editable=False, verbose_name='是否退款')),
                ('is_verify', models.BooleanField(default=False, editable=False, help_text='核销后，订单状态会自动改为待评价', verbose_name='是否已核销')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='BaykeShopOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('satisfaction', models.SmallIntegerField(choices=[(1, '好评'), (2, '中评'), (3, '差评')], default=1, verbose_name='评价满意度')),
                ('score', models.SmallIntegerField(default=5, help_text='1-5分', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='评价分数')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.baykeshoporder', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单评价',
                'verbose_name_plural': '订单评价',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='BaykeShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('quantity', models.PositiveIntegerField(verbose_name='购买数量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.baykeshoporder', verbose_name='订单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.baykeshopsku', verbose_name='商品')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='BaykeShopOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('content', models.TextField(verbose_name='日志内容')),
                ('type', models.SmallIntegerField(choices=[(0, '待支付'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成'), (5, '已取消'), (6, '已退款'), (7, '待核销')], verbose_name='日志类型')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.baykeshoporder', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '订单日志',
                'verbose_name_plural': '订单日志',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='baykeshoporder',
            constraint=models.UniqueConstraint(fields=('user', 'order_sn'), name='unique_order_sn'),
        ),
        migrations.AddConstraint(
            model_name='baykeshoporderitem',
            constraint=models.UniqueConstraint(fields=('order', 'sku'), name='unique_order_sku'),
        ),
    ]
