# Generated by Django 5.1.2 on 2024-11-25 08:02

import baykeshop.apps.core.validators._validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('name', models.CharField(max_length=20, verbose_name='收件人')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('city', models.CharField(max_length=20, verbose_name='城市')),
                ('district', models.CharField(max_length=20, verbose_name='区域')),
                ('detail_address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('phone', models.CharField(max_length=11, validators=[baykeshop.apps.core.validators._validators.validate_phone], verbose_name='手机号')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户地址',
                'verbose_name_plural': '用户地址',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('nickname', models.CharField(default='', max_length=50, verbose_name='昵称')),
                ('avatar', models.ImageField(default='', upload_to='avatar/%Y/%m', validators=[baykeshop.apps.core.validators._validators.validate_image_size], verbose_name='头像')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('empty', '未知')], default='male', max_length=10, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[baykeshop.apps.core.validators._validators.validate_phone], verbose_name='手机号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['-create_time'],
            },
        ),
    ]
