[project]
name = "baykeshop"
version = "2.0.0-alpha"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "轻编程", email = "2539909370@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django==4.2.16",
    "pillow>=11.0.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
