[project]
name = "baykeshop"
version = "2.0.0-alpha"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "轻编程", email = "2539909370@qq.com" }
]
requires-python = ">=3.11.10"
dependencies = [
    "alipay-sdk-python>=3.7.345",
    "djangorestframework>=3.15.2",
    "pillow>=11.0.0",
    "pyecharts>=2.0.7",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
