# Generated by Django 4.2.16 on 2024-11-28 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykegallery',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='图片名称'),
        ),
    ]
