# Generated by Django 5.1.2 on 2024-11-25 08:02

import baykeshop.apps.core.validators._validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('file', models.ImageField(upload_to='upload/%Y/%m/%d', validators=[baykeshop.apps.core.validators._validators.validate_image_size], verbose_name='文件')),
            ],
            options={
                'verbose_name': '上传图片',
                'verbose_name_plural': '上传图片',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='ExtendSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('site_title', models.CharField(help_text='用于SEO优化, 前后台显示的站点名称', max_length=50, verbose_name='标题')),
                ('site_header', models.CharField(blank=True, default='', help_text='管理后台使用的站点名称', max_length=50, verbose_name='头部')),
                ('index_title', models.CharField(blank=True, default='', help_text='管理后台首页标题', max_length=50, verbose_name='首页标题')),
                ('logo', models.ImageField(blank=True, default='', help_text='站点Logo', upload_to='site/logo/%Y/%m/%d', verbose_name='logo')),
                ('description', models.TextField(blank=True, default='', help_text='用于SEO优化, 前台显示的站点描述', verbose_name='描述')),
                ('keywords', models.TextField(blank=True, default='', help_text='用于SEO优化, 前台显示的站点关键字', verbose_name='关键字')),
                ('icp_record', models.CharField(blank=True, default='陕ICP备123456789', max_length=50, verbose_name='备案号')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend_site', to='sites.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '站点扩展',
                'verbose_name_plural': '站点扩展',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='ExtendSiteEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('host', models.CharField(max_length=50, verbose_name='主机')),
                ('port', models.PositiveSmallIntegerField(default=465, verbose_name='端口')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('is_ssl', models.BooleanField(default=False, verbose_name='是否SSL')),
                ('is_tls', models.BooleanField(default=False, verbose_name='是否TLS')),
                ('from_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='发件人')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend_site_email', to='sites.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '站点邮箱配置',
                'verbose_name_plural': '站点邮箱配置',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='ExtandSiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('key', models.CharField(max_length=50, verbose_name='键')),
                ('value', models.TextField(verbose_name='值')),
                ('description', models.CharField(blank=True, default='', max_length=50, verbose_name='描述')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extend_site_config', to='sites.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '站点扩展配置',
                'verbose_name_plural': '站点扩展配置',
                'ordering': ('-create_time',),
                'constraints': [models.UniqueConstraint(fields=('site', 'key'), name='unique_site_key')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_show', models.BooleanField(default=True, editable=False, help_text='不显示在页面上', verbose_name='是否显示')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='对象ID')),
                ('ip', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP')),
                ('pv', models.PositiveBigIntegerField(verbose_name='PV')),
                ('uv', models.PositiveBigIntegerField(verbose_name='UV')),
                ('date', models.DateField(verbose_name='日期')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
            ],
            options={
                'verbose_name': '分析数据',
                'verbose_name_plural': '分析数据',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='core_visit_date_e33ba1_idx'), models.Index(fields=['content_type', 'object_id'], name='core_visit_content_dbc3ae_idx'), models.Index(fields=['content_type', 'object_id', 'date'], name='core_visit_content_6f30da_idx')],
            },
        ),
    ]
