# Generated by Django 4.2.16 on 2024-11-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DictModel',
            new_name='BaykeDictModel',
        ),
    ]
