# Generated by Django 4.2.16 on 2024-11-29 14:36

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sites', '0002_alter_domain_unique'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='是否删除')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='对象ID')),
                ('ip', models.GenericIPAddressField(default='127.0.0.1', verbose_name='IP')),
                ('pv', models.PositiveBigIntegerField(verbose_name='PV')),
                ('uv', models.PositiveBigIntegerField(verbose_name='UV')),
                ('date', models.DateField(verbose_name='日期')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '分析数据',
                'verbose_name_plural': '分析数据',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='system_visi_date_8fe15a_idx'), models.Index(fields=['content_type', 'object_id'], name='system_visi_content_0cf1e0_idx'), models.Index(fields=['content_type', 'object_id', 'date'], name='system_visi_content_8e96af_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
