# Generated by Django 4.2.16 on 2024-11-27 07:38

import baykeshop.contrib.system.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_baykedictmodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykedictmodel',
            name='value',
            field=models.TextField(help_text='\n            布尔值：true/false; \n            键值对：key1:value1一行一对;\n            list:value1,value2一行一个值;\n            json:{"key1":"value1"}\n        ', validators=[baykeshop.contrib.system.validators.validate_dict_value], verbose_name='值'),
        ),
    ]
