# Generated by Django 4.1.7 on 2023-04-12 08:58

import baykeshop.models.tinymce_field
from django.conf import settings
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='分类图标')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
                ('keywords', models.CharField(blank=True, default='', max_length=150, verbose_name='关键字')),
                ('pic', models.ImageField(max_length=200, upload_to='product/category/', verbose_name='封面图')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否导航')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykecategory')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
                ('keywords', models.CharField(blank=True, default='', max_length=150, verbose_name='关键字')),
                ('content', baykeshop.models.tinymce_field.TinymceField(tinymce={'automatic_uploads': True, 'browser_spellcheck': True, 'contextmenu': False, 'file_picker_types': 'file image media', 'image_title': False, 'images_file_types': 'jpg,svg,webp,png,gif', 'images_reuse_filename': True, 'images_upload_url': '/upload/tinymce/', 'plugins': ['advlist', 'autolink', 'link', 'image', 'lists', 'charmap', 'preview', 'anchor', 'pagebreak', 'searchreplace', 'wordcount', 'visualblocks', 'visualchars', 'code', 'fullscreen', 'insertdatetime', 'media', 'table', 'emoticons', 'template', 'help'], 'toolbar': 'undo redo | styles | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media | forecolor backcolor emoticons'}, verbose_name='详情')),
                ('after_sale', baykeshop.models.tinymce_field.TinymceField(blank=True, default='', tinymce={'automatic_uploads': True, 'browser_spellcheck': True, 'contextmenu': False, 'file_picker_types': 'file image media', 'image_title': False, 'images_file_types': 'jpg,svg,webp,png,gif', 'images_reuse_filename': True, 'images_upload_url': '/upload/tinymce/', 'plugins': ['advlist', 'autolink', 'link', 'image', 'lists', 'charmap', 'preview', 'anchor', 'pagebreak', 'searchreplace', 'wordcount', 'visualblocks', 'visualchars', 'code', 'fullscreen', 'insertdatetime', 'media', 'table', 'emoticons', 'template', 'help'], 'toolbar': 'undo redo | styles | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media | forecolor backcolor emoticons'}, verbose_name='售后服务')),
                ('pic', models.ImageField(max_length=200, upload_to='pic/%Y/', verbose_name='主图')),
                ('categorys', models.ManyToManyField(blank=True, to='baykeshop.baykecategory', verbose_name='分类')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='分类图标')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
                ('keywords', models.CharField(blank=True, default='', max_length=150, verbose_name='关键字')),
                ('sort', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['-sort'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('pic', models.ImageField(max_length=200, upload_to='pic/%Y/', verbose_name='主图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='售价')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='原价')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('sales', models.PositiveIntegerField(default=0, editable=False, verbose_name='销量')),
                ('num', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='商品编号')),
                ('weight', models.PositiveSmallIntegerField(default=0, help_text='单位：千克', verbose_name='重量')),
                ('volume', models.PositiveSmallIntegerField(default=0, help_text='单位：立方米', verbose_name='体积')),
                ('is_release', models.BooleanField(default=True, verbose_name='上架')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykegoods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
                'ordering': ['-add_date'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='规格')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '规格',
                'verbose_name_plural': '规格',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('avatar', models.ImageField(blank=True, default='avatar/default.jpg', max_length=200, upload_to='avatar/', verbose_name='头像')),
                ('nickname', models.CharField(blank=True, default='', max_length=30, verbose_name='昵称')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='余额')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeUserBalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('change_status', models.PositiveSmallIntegerField(blank=True, choices=[(1, '增加'), (2, '支出')], null=True)),
                ('change_way', models.PositiveSmallIntegerField(choices=[(1, '线上充值'), (2, '管理员手动更改'), (3, '余额抵扣商品')], default=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '余额明细',
                'verbose_name_plural': '余额明细',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeSpecOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='规格值')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykespec', verbose_name='规格')),
            ],
            options={
                'verbose_name': '规格值',
                'verbose_name_plural': '规格值',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeShopingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baykeshop.baykeproduct', verbose_name='商品')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeShopAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='签收人')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, default='', max_length=50, verbose_name='邮箱')),
                ('province', models.CharField(max_length=150, verbose_name='省')),
                ('city', models.CharField(max_length=150, verbose_name='市')),
                ('county', models.CharField(max_length=150, verbose_name='区/县')),
                ('address', models.CharField(max_length=150, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='设为默认')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '收货地址',
                'verbose_name_plural': '收货地址',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='baykeproduct',
            name='options',
            field=models.ManyToManyField(blank=True, to='baykeshop.baykespecoptions', verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='baykeproduct',
            name='site',
            field=models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.CreateModel(
            name='BaykePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='分类图标')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
                ('keywords', models.CharField(blank=True, default='', max_length=150, verbose_name='关键字')),
                ('sort', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('menus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykemenu', verbose_name='菜单')),
                ('permission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.permission', verbose_name='权限')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '菜单权限',
                'verbose_name_plural': '菜单权限',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeGoodsBanners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('img', models.ImageField(max_length=200, upload_to='upload/', verbose_name='图片')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='图片说明')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykegoods', verbose_name='商品')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaykeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('img', models.ImageField(max_length=200, upload_to='upload/', verbose_name='图片')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='图片说明')),
                ('place', models.CharField(blank=True, help_text='留空则为首页banner，否则为指定位置banner', max_length=50, null=True, unique=True, verbose_name='位置标识')),
                ('target_url', models.CharField(blank=True, default='', max_length=150, verbose_name='跳转地址')),
                ('sort', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['sort'],
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='baykeshopingcart',
            constraint=models.UniqueConstraint(fields=('owner', 'sku'), name='unique_owner_sku'),
        ),
    ]
