# Generated by Django 4.1.7 on 2023-04-05 13:32

import baykeshop.models.tinymce_field
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
                ('keywords', models.CharField(blank=True, default='', max_length=150, verbose_name='关键字')),
                ('content', baykeshop.models.tinymce_field.TinymceField(tinymce={'automatic_uploads': True, 'browser_spellcheck': True, 'contextmenu': False, 'file_picker_types': 'file image media', 'image_title': False, 'images_file_types': 'jpg,svg,webp,png,gif', 'images_reuse_filename': True, 'images_upload_url': '/upload/tinymce/', 'plugins': ['advlist', 'autolink', 'link', 'image', 'lists', 'charmap', 'preview', 'anchor', 'pagebreak', 'searchreplace', 'wordcount', 'visualblocks', 'visualchars', 'code', 'fullscreen', 'insertdatetime', 'media', 'table', 'emoticons', 'template', 'help'], 'toolbar': 'undo redo | styles | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media | forecolor backcolor emoticons'}, verbose_name='详情')),
                ('after_sale', baykeshop.models.tinymce_field.TinymceField(blank=True, default='', tinymce={'automatic_uploads': True, 'browser_spellcheck': True, 'contextmenu': False, 'file_picker_types': 'file image media', 'image_title': False, 'images_file_types': 'jpg,svg,webp,png,gif', 'images_reuse_filename': True, 'images_upload_url': '/upload/tinymce/', 'plugins': ['advlist', 'autolink', 'link', 'image', 'lists', 'charmap', 'preview', 'anchor', 'pagebreak', 'searchreplace', 'wordcount', 'visualblocks', 'visualchars', 'code', 'fullscreen', 'insertdatetime', 'media', 'table', 'emoticons', 'template', 'help'], 'toolbar': 'undo redo | styles | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media | forecolor backcolor emoticons'}, verbose_name='售后服务')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaykeSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='规格')),
            ],
            options={
                'verbose_name': '规格',
                'verbose_name_plural': '规格',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaykeSpecOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='规格值')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykespec', verbose_name='规格')),
            ],
            options={
                'verbose_name': '规格值',
                'verbose_name_plural': '规格值',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaykeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('pic', models.ImageField(max_length=200, upload_to='pic/%Y/', verbose_name='主图')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='售价')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('num', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='商品编号')),
                ('weight', models.PositiveSmallIntegerField(default=0, help_text='单位：千克', verbose_name='重量')),
                ('volume', models.PositiveSmallIntegerField(default=0, help_text='单位：立方米', verbose_name='体积')),
                ('is_release', models.BooleanField(default=True, verbose_name='上架')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykegoods', verbose_name='商品')),
                ('options', models.ManyToManyField(blank=True, to='baykeshop.baykespecoptions', verbose_name='规格')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
            },
        ),
    ]
