# Generated by Django 4.1.7 on 2023-04-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='分类图标')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='描述')),
                ('keywords', models.CharField(blank=True, default='', max_length=150, verbose_name='关键字')),
                ('pic', models.ImageField(max_length=200, upload_to='product/category/', verbose_name='封面图')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否导航')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['-pub_date'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='baykegoods',
            name='categorys',
            field=models.ManyToManyField(blank=True, to='baykeshop.baykecategory', verbose_name='分类'),
        ),
    ]
