# Generated by Django 4.1.7 on 2023-04-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykecategory',
            name='pic',
            field=models.ImageField(blank=True, default='catedefault.png', max_length=200, upload_to='product/category/', verbose_name='封面图'),
        ),
    ]
