# Generated by Django 4.1.7 on 2023-04-06 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0002_baykecategory_baykegoods_categorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykecategory'),
        ),
    ]
