# Generated by Django 4.1.7 on 2023-04-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0002_alter_baykecategory_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykegoods',
            name='freight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='运费'),
        ),
    ]
