# Generated by Django 4.1.7 on 2023-04-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0004_baykeorderinfo_baykeordergoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeorderinfo',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='商品总金额'),
        ),
    ]
