# Generated by Django 4.1.7 on 2023-04-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0005_alter_baykeorderinfo_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeorderinfo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='商品总金额'),
        ),
    ]
