# Generated by Django 4.1.7 on 2023-04-07 01:13

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('baykeshop', '0005_alter_baykecategory_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaykeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('img', models.ImageField(max_length=200, upload_to='upload/', verbose_name='图片')),
                ('desc', models.CharField(blank=True, default='', max_length=150, verbose_name='图片说明')),
                ('place', models.CharField(blank=True, help_text='留空则为首页banner，否则为指定位置banner', max_length=50, null=True, unique=True, verbose_name='位置标识')),
                ('target_url', models.CharField(blank=True, default='', max_length=150, verbose_name='跳转地址')),
                ('sort', models.PositiveSmallIntegerField(default=1, verbose_name='排序')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['sort'],
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
