# Generated by Django 4.1.7 on 2023-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0006_baykebanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykeproduct',
            options={'verbose_name': '商品规格', 'verbose_name_plural': '商品规格'},
        ),
        migrations.AddField(
            model_name='baykegoods',
            name='pic',
            field=models.ImageField(default=1, max_length=200, upload_to='pic/%Y/', verbose_name='主图'),
            preserve_default=False,
        ),
    ]
