# Generated by Django 4.1.7 on 2023-04-17 03:52

from django.conf import settings
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baykeshop', '0006_alter_baykeorderinfo_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeuserbalancelog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='BaykeOrderInfoComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('pub_date', models.DateTimeField(auto_now=True)),
                ('is_del', models.BooleanField(default=False, editable=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('tag', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='标记')),
                ('content', models.CharField(max_length=200, verbose_name='留言内容')),
                ('comment_choices', models.PositiveSmallIntegerField(choices=[(5, '好评'), (3, '中评'), (1, '差评')], default=5, verbose_name='评分')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('site', models.ForeignKey(blank=True, help_text='关联站点，如果选择，该信息仅在指定站点显示', null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': '商品评价',
                'verbose_name_plural': '商品评价',
                'ordering': ['-add_date'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
