# Generated by Django 4.1.7 on 2023-04-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0007_alter_baykeproduct_options_baykegoods_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykeproduct',
            options={'ordering': ['-add_date'], 'verbose_name': '商品规格', 'verbose_name_plural': '商品规格'},
        ),
        migrations.AddField(
            model_name='baykeproduct',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='baykeproduct',
            name='sales',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='销量'),
        ),
    ]
