# Generated by Django 4.1.7 on 2023-04-11 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baykeshop', '0009_baykegoodsbanners_baykegoods_banners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baykegoods',
            name='banners',
        ),
        migrations.AddField(
            model_name='baykegoodsbanners',
            name='goods',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baykeshop.baykegoods', verbose_name='商品'),
            preserve_default=False,
        ),
    ]
