# Generated by Django 5.1.4 on 2024-12-05 04:51

import django.contrib.sites.managers
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykearticlecategory',
            options={'ordering': ['-created_time'], 'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
        migrations.AlterModelOptions(
            name='baykearticletags',
            options={'ordering': ['-created_time'], 'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
        migrations.CreateModel(
            name='BaykeSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, editable=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('icon', models.CharField(blank=True, default='mdi mdi-menu', max_length=50, verbose_name='图标')),
                ('module', models.CharField(choices=[('search', '搜索'), ('archive', '归档'), ('nav', '导航栏'), ('tags', '标签'), ('custom', '自定义')], default='custom', max_length=255, verbose_name='模块')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('site', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点')),
            ],
            options={
                'verbose_name': '侧边栏',
                'verbose_name_plural': '侧边栏',
                'ordering': ['order'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('current_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
