# Generated by Django 5.1.4 on 2024-12-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_baykearticlecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykesidebar',
            name='content',
            field=models.TextField(blank=True, default='', help_text='自定义内容，仅在自定义模块下生效，支持html语法', verbose_name='自定义内容'),
        ),
    ]
