# Generated by Django 5.1.4 on 2024-12-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_baykesidebar_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykesidebar',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
