# Generated by Django 5.1.4 on 2024-12-07 09:30

import baykeshop.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_baykesidebar_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykearticlecontent',
            name='content',
            field=baykeshop.db.fields.RichTextField(verbose_name='内容'),
        ),
    ]
