# Generated by Django 4.2.16 on 2024-11-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baykeshoporders',
            name='total_price',
        ),
    ]
