# Generated by Django 4.2.16 on 2024-11-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopgoods',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='商品描述'),
        ),
        migrations.AddField(
            model_name='baykeshopgoods',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='商品关键字'),
        ),
        migrations.AlterField(
            model_name='baykeshopbrand',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopcarts',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopcategory',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoods',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoodssku',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshoporders',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopordersgoods',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
    ]
