# Generated by Django 4.2.16 on 2024-11-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_baykeshopgoods_description_baykeshopgoods_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopgoodssku',
            name='sales',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoodssku',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='库存'),
        ),
    ]
