# Generated by Django 4.2.16 on 2024-11-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_baykeshoporders_total_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='baykeshopgoodsimages',
            name='unique_goods_image',
        ),
    ]
