# Generated by Django 4.2.16 on 2024-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_baykeshopgoodsimages_unique_goods_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baykeshopgoodsimages',
            name='is_main',
        ),
        migrations.AlterField(
            model_name='baykeshopgoodsimages',
            name='image',
            field=models.ImageField(help_text='_(建议尺寸: 800*800，排在第一个的图片会作为商品主图)', upload_to='goods/images', verbose_name='商品图片'),
        ),
    ]
