# Generated by Django 4.2.16 on 2024-11-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_baykeshopgoodssku_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopgoods',
            name='images',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='商品轮播图'),
        ),
    ]
