# Generated by Django 4.2.16 on 2024-11-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_baykeshopgoodsimages_is_main_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baykeshopgoods',
            name='spec_type',
        ),
    ]
