# Generated by Django 4.2.16 on 2024-11-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_baykeshopgoods_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporders',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='是否核销订单'),
        ),
        migrations.AlterField(
            model_name='baykeshoporders',
            name='status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '待发货'), (2, '待收货'), (3, '已完成'), (4, '已取消'), (5, '已过期'), (6, '待核销'), (7, '已核销')], default=0, verbose_name='订单状态'),
        ),
    ]
