# Generated by Django 4.2.16 on 2024-11-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_baykeshopgoods_spec_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopgoods',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='商品推荐'),
        ),
    ]
