# Generated by Django 4.2.16 on 2024-11-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_baykeshoporders_is_verify_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baykeshopgoods',
            name='is_multi',
        ),
        migrations.AddField(
            model_name='baykeshopgoods',
            name='goods_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '普通商品'), (2, '虚拟商品')], default=1, verbose_name='商品类型'),
        ),
        migrations.AddField(
            model_name='baykeshopgoods',
            name='spec_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '单规格'), (2, '多规格')], default=1, verbose_name='商品规格类型'),
        ),
        migrations.AddField(
            model_name='baykeshopgoods',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '上架'), (2, '下架')], default=1, verbose_name='商品状态'),
        ),
        migrations.RemoveField(
            model_name='baykeshopgoods',
            name='category',
        ),
        migrations.AddField(
            model_name='baykeshopgoods',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.baykeshopcategory', verbose_name='商品分类'),
        ),
    ]
