# Generated by Django 4.2.16 on 2024-12-04 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_baykeshopgoods_is_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporders',
            name='status',
            field=models.IntegerField(choices=[(0, '未支付'), (1, '待发货'), (2, '待收货'), (3, '待评价'), (4, '已完成'), (5, '已取消'), (6, '已退款'), (7, '待核销')], default=0, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='baykeshopordersgoods',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.baykeshopgoodssku', verbose_name='商品'),
        ),
    ]
