# Generated by Django 4.2.16 on 2024-11-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_baykeshopspec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baykeshopspec',
            options={'ordering': ['-created_time'], 'verbose_name': '规格模版', 'verbose_name_plural': '规格模版'},
        ),
    ]
