# Generated by Django 4.2.16 on 2024-12-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_baykeshoporders_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshoporders',
            name='pay_sn',
            field=models.CharField(blank=True, default='', max_length=125, verbose_name='支付流水号'),
        ),
        migrations.AlterField(
            model_name='baykeshoporders',
            name='pay_type',
            field=models.IntegerField(choices=[(0, '支付宝'), (1, '微信支付'), (2, '货到付款')], default=0, verbose_name='支付方式'),
        ),
    ]
