# Generated by Django 5.1.4 on 2024-12-04 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_baykeshoporderscomment'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopbrand',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopcarts',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopcategory',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoods',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoodsimages',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopgoodssku',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshoporders',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshoporderscomment',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='baykeshoporderscomment',
            name='score',
            field=models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='baykeshoporderscomment',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopordersgoods',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='baykeshopspec',
            name='site',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='站点'),
        ),
    ]
