# Generated by Django 5.1.4 on 2024-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_baykeshopbrand_site_alter_baykeshopcarts_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baykeshopcategory',
            name='is_floor',
            field=models.BooleanField(default=False, verbose_name='是否楼层'),
        ),
        migrations.AddField(
            model_name='baykeshopcategory',
            name='is_nav',
            field=models.BooleanField(default=False, verbose_name='是否导航'),
        ),
    ]
