# Generated by Django 5.1.4 on 2024-12-07 07:07

import baykeshop.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_baykeshopcategory_is_floor_baykeshopcategory_is_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baykeshopgoods',
            name='detail',
            field=baykeshop.db.fields.RichTextField(blank=True, null=True, verbose_name='商品详情'),
        ),
        migrations.AlterField(
            model_name='baykeshoporders',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='是否已核销'),
        ),
    ]
